import { Match } from './types';

export const mockMatches: Match[] = [
  {
    id: '1',
    sport: 'football',
    team1: 'Manchester United',
    team2: 'Liverpool',
    score1: 2,
    score2: 1,
    status: 'live',
    startTime: new Date(Date.now() - 45 * 60 * 1000),
    tournament: 'Premier League',
    isEsports: false,
    currentMinute: 67,
    totalMinutes: 90,
    hasVip: true,
  },
  {
    id: '2',
    sport: 'valorant',
    team1: 'Sentinels',
    team2: 'LOUD',
    score1: 1,
    score2: 1,
    status: 'live',
    startTime: new Date(Date.now() - 30 * 60 * 1000),
    tournament: 'VCT Americas 2024',
    isEsports: true,
    currentMinute: 23,
    totalMinutes: 60,
  },
  {
    id: '3',
    sport: 'basketball',
    team1: 'LA Lakers',
    team2: 'Boston Celtics',
    score1: 89,
    score2: 92,
    status: 'live',
    startTime: new Date(Date.now() - 90 * 60 * 1000),
    tournament: 'NBA Playoffs',
    isEsports: false,
    currentMinute: 35,
    totalMinutes: 48,
  },
  {
    id: '4',
    sport: 'lol',
    team1: 'T1',
    team2: 'Gen.G',
    status: 'upcoming',
    startTime: new Date(Date.now() + 30 * 60 * 1000),
    tournament: 'LCK Spring Split',
    isEsports: true,
  },
  {
    id: '5',
    sport: 'football',
    team1: 'Real Madrid',
    team2: 'Barcelona',
    status: 'upcoming',
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    tournament: 'La Liga',
    isEsports: false,
    hasVip: true,
  },
  {
    id: '6',
    sport: 'csgo',
    team1: 'NAVI',
    team2: 'FaZe Clan',
    status: 'upcoming',
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
    tournament: 'IEM Katowice 2024',
    isEsports: true,
  },
  {
    id: '7',
    sport: 'tennis',
    team1: 'Novak Djokovic',
    team2: 'Carlos Alcaraz',
    status: 'upcoming',
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
    tournament: 'Wimbledon Final',
    isEsports: false,
    hasVip: true,
  },
  {
    id: '8',
    sport: 'basketball',
    team1: 'Golden State Warriors',
    team2: 'Miami Heat',
    status: 'upcoming',
    startTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
    tournament: 'NBA Regular Season',
    isEsports: false,
  },
  {
    id: '9',
    sport: 'football',
    team1: 'Manchester City',
    team2: 'Dortmund',
    score1: 3,
    score2: 2,
    status: 'finished',
    startTime: new Date(Date.now() - 4 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 3 * 60 * 60 * 1000),
    tournament: 'Bundesliga',
    isEsports: false,
  },
  {
    id: '10',
    sport: 'csgo',
    team1: 'Vitality',
    team2: 'G2',
    score1: 2,
    score2: 0,
    status: 'finished',
    startTime: new Date(Date.now() - 5 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 4 * 60 * 60 * 1000),
    tournament: 'BLAST Premier',
    isEsports: true,
  },
  {
    id: '11',
    sport: 'valorant',
    team1: 'Paper Rex',
    team2: 'DRX',
    score1: 2,
    score2: 1,
    status: 'finished',
    startTime: new Date(Date.now() - 6 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 5 * 60 * 60 * 1000),
    tournament: 'VCT Pacific',
    isEsports: true,
  },
  {
    id: '12',
    sport: 'basketball',
    team1: 'Chicago Bulls',
    team2: 'New York Knicks',
    score1: 105,
    score2: 112,
    status: 'finished',
    startTime: new Date(Date.now() - 8 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 6 * 60 * 60 * 1000),
    tournament: 'NBA Regular Season',
    isEsports: false,
  },
];