export interface Player {
  number: number;
  name: string;
  position: string;
}

export interface RecentResult {
  opponent: string;
  score: string;
  result: 'W' | 'D' | 'L';
  date: string;
  tournament: string;
}

export interface TeamInfo {
  name: string;
  shortName: string;
  stadium: string;
  coach: string;
  founded: number;
  country: string;
  color: string; // tailwind gradient
  players: Player[];
  recentResults: RecentResult[];
}

export const teamDatabase: Record<string, TeamInfo> = {
  'Manchester United': {
    name: 'Manchester United',
    shortName: 'MAN UTD',
    stadium: 'Old Trafford',
    coach: 'Erik ten Hag',
    founded: 1878,
    country: 'Anh',
    color: 'from-red-600 to-rose-700',
    players: [
      { number: 1,  name: 'André Onana',       position: 'Thủ môn' },
      { number: 2,  name: 'Victor Lindelöf',   position: 'Hậu vệ' },
      { number: 5,  name: 'Harry Maguire',      position: 'Hậu vệ' },
      { number: 6,  name: 'Lisandro Martínez',  position: 'Hậu vệ' },
      { number: 23, name: 'Luke Shaw',           position: 'Hậu vệ' },
      { number: 8,  name: 'Bruno Fernandes',    position: 'Tiền vệ' },
      { number: 14, name: 'Christian Eriksen',  position: 'Tiền vệ' },
      { number: 18, name: 'Casemiro',            position: 'Tiền vệ' },
      { number: 10, name: 'Marcus Rashford',    position: 'Tiền đạo' },
      { number: 11, name: 'Rasmus Højlund',     position: 'Tiền đạo' },
      { number: 21, name: 'Antony',              position: 'Tiền đạo' },
    ],
    recentResults: [
      { opponent: 'Liverpool',        score: '2–1', result: 'W', date: '01/04/2024', tournament: 'Premier League' },
      { opponent: 'Arsenal',          score: '0–1', result: 'L', date: '22/03/2024', tournament: 'Premier League' },
      { opponent: 'Fulham',           score: '2–2', result: 'D', date: '14/03/2024', tournament: 'Premier League' },
      { opponent: 'Everton',          score: '3–1', result: 'W', date: '09/03/2024', tournament: 'FA Cup' },
      { opponent: 'Manchester City',  score: '1–3', result: 'L', date: '03/03/2024', tournament: 'Premier League' },
    ],
  },
  'Liverpool': {
    name: 'Liverpool',
    shortName: 'LIV',
    stadium: 'Anfield',
    coach: 'Jürgen Klopp',
    founded: 1892,
    country: 'Anh',
    color: 'from-red-500 to-red-700',
    players: [
      { number: 1,  name: 'Alisson Becker',       position: 'Thủ môn' },
      { number: 66, name: 'Trent Alexander-Arnold',position: 'Hậu vệ' },
      { number: 4,  name: 'Virgil van Dijk',       position: 'Hậu vệ' },
      { number: 12, name: 'Joe Gómez',              position: 'Hậu vệ' },
      { number: 26, name: 'Andrew Robertson',       position: 'Hậu vệ' },
      { number: 3,  name: 'Wataru Endō',            position: 'Tiền vệ' },
      { number: 8,  name: 'Dominik Szoboszlai',    position: 'Tiền vệ' },
      { number: 38, name: 'Ryan Gravenberch',       position: 'Tiền vệ' },
      { number: 11, name: 'Mohamed Salah',          position: 'Tiền đạo' },
      { number: 9,  name: 'Darwin Núñez',           position: 'Tiền đạo' },
      { number: 20, name: 'Diogo Jota',             position: 'Tiền đạo' },
    ],
    recentResults: [
      { opponent: 'Manchester United', score: '1–2', result: 'L', date: '01/04/2024', tournament: 'Premier League' },
      { opponent: 'Brentford',         score: '4–1', result: 'W', date: '24/03/2024', tournament: 'Premier League' },
      { opponent: 'Manchester City',   score: '1–1', result: 'D', date: '16/03/2024', tournament: 'Premier League' },
      { opponent: 'Sparta Prague',     score: '6–1', result: 'W', date: '07/03/2024', tournament: 'Europa League' },
      { opponent: 'Nottm Forest',      score: '1–0', result: 'W', date: '02/03/2024', tournament: 'Premier League' },
    ],
  },
  'Real Madrid': {
    name: 'Real Madrid',
    shortName: 'RMA',
    stadium: 'Santiago Bernabéu',
    coach: 'Carlo Ancelotti',
    founded: 1902,
    country: 'Tây Ban Nha',
    color: 'from-purple-600 to-blue-700',
    players: [
      { number: 1,  name: 'Thibaut Courtois', position: 'Thủ môn' },
      { number: 2,  name: 'Dani Carvajal',    position: 'Hậu vệ' },
      { number: 3,  name: 'Éder Militão',     position: 'Hậu vệ' },
      { number: 22, name: 'Antonio Rüdiger',   position: 'Hậu vệ' },
      { number: 23, name: 'Ferland Mendy',     position: 'Hậu vệ' },
      { number: 10, name: 'Luka Modrić',       position: 'Tiền vệ' },
      { number: 15, name: 'Federico Valverde', position: 'Tiền vệ' },
      { number: 8,  name: 'Toni Kroos',        position: 'Tiền vệ' },
      { number: 9,  name: 'Karim Benzema',     position: 'Tiền đạo' },
      { number: 7,  name: 'Vinícius Jr.',      position: 'Tiền đạo' },
      { number: 11, name: 'Rodrygo',           position: 'Tiền đạo' },
    ],
    recentResults: [
      { opponent: 'Barcelona',     score: '3–2', result: 'W', date: '21/04/2024', tournament: 'La Liga' },
      { opponent: 'Villarreal',    score: '5–0', result: 'W', date: '08/04/2024', tournament: 'La Liga' },
      { opponent: 'Man City',      score: '1–1', result: 'D', date: '09/04/2024', tournament: 'Champions League' },
      { opponent: 'Celta Vigo',    score: '4–0', result: 'W', date: '06/04/2024', tournament: 'La Liga' },
      { opponent: 'Athletic Club', score: '0–1', result: 'L', date: '31/03/2024', tournament: 'La Liga' },
    ],
  },
  'Barcelona': {
    name: 'Barcelona',
    shortName: 'BAR',
    stadium: 'Estadi Olímpic Lluís Companys',
    coach: 'Xavi Hernández',
    founded: 1899,
    country: 'Tây Ban Nha',
    color: 'from-blue-700 to-red-600',
    players: [
      { number: 1,  name: 'Marc-André ter Stegen', position: 'Thủ môn' },
      { number: 2,  name: 'João Cancelo',           position: 'Hậu vệ' },
      { number: 15, name: 'Iñigo Martínez',         position: 'Hậu vệ' },
      { number: 3,  name: 'Ronald Araújo',           position: 'Hậu vệ' },
      { number: 30, name: 'Alejandro Balde',         position: 'Hậu vệ' },
      { number: 5,  name: 'Ilkay Gündogan',         position: 'Tiền vệ' },
      { number: 8,  name: 'Pedri',                   position: 'Tiền vệ' },
      { number: 16, name: 'Fermín López',            position: 'Tiền vệ' },
      { number: 9,  name: 'Robert Lewandowski',     position: 'Tiền đạo' },
      { number: 11, name: 'Raphinha',                position: 'Tiền đạo' },
      { number: 17, name: 'Lamine Yamal',            position: 'Tiền đạo' },
    ],
    recentResults: [
      { opponent: 'Real Madrid',  score: '2–3', result: 'L', date: '21/04/2024', tournament: 'La Liga' },
      { opponent: 'PSG',          score: '1–4', result: 'L', date: '16/04/2024', tournament: 'Champions League' },
      { opponent: 'Valencia',     score: '4–2', result: 'W', date: '29/03/2024', tournament: 'La Liga' },
      { opponent: 'Las Palmas',   score: '3–0', result: 'W', date: '16/03/2024', tournament: 'La Liga' },
      { opponent: 'Napoli',       score: '3–1', result: 'W', date: '12/03/2024', tournament: 'Champions League' },
    ],
  },
  'LA Lakers': {
    name: 'LA Lakers',
    shortName: 'LAL',
    stadium: 'Crypto.com Arena',
    coach: 'Darvin Ham',
    founded: 1947,
    country: 'Mỹ',
    color: 'from-yellow-500 to-purple-700',
    players: [
      { number: 6,  name: 'LeBron James',         position: 'Small Forward' },
      { number: 3,  name: 'Anthony Davis',         position: 'Power Forward' },
      { number: 1,  name: 'D\'Angelo Russell',      position: 'Point Guard' },
      { number: 5,  name: 'Austin Reaves',         position: 'Shooting Guard' },
      { number: 10, name: 'Rui Hachimura',         position: 'Power Forward' },
      { number: 11, name: 'Jaxson Hayes',          position: 'Center' },
      { number: 14, name: 'Gabe Vincent',          position: 'Point Guard' },
      { number: 8,  name: 'Taurean Prince',        position: 'Small Forward' },
    ],
    recentResults: [
      { opponent: 'Boston Celtics',  score: '89–92', result: 'L', date: '01/04/2024', tournament: 'NBA Playoffs' },
      { opponent: 'Warriors',        score: '121–110', result: 'W', date: '28/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Clippers',        score: '116–103', result: 'W', date: '24/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Nuggets',         score: '114–123', result: 'L', date: '19/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Suns',            score: '130–106', result: 'W', date: '15/03/2024', tournament: 'NBA Regular' },
    ],
  },
  'Boston Celtics': {
    name: 'Boston Celtics',
    shortName: 'BOS',
    stadium: 'TD Garden',
    coach: 'Joe Mazzulla',
    founded: 1946,
    country: 'Mỹ',
    color: 'from-green-700 to-emerald-800',
    players: [
      { number: 0,  name: 'Jayson Tatum',    position: 'Small Forward' },
      { number: 7,  name: 'Jaylen Brown',    position: 'Shooting Guard' },
      { number: 42, name: 'Al Horford',      position: 'Power Forward' },
      { number: 36, name: 'Marcus Smart',    position: 'Point Guard' },
      { number: 44, name: 'Robert Williams', position: 'Center' },
      { number: 8,  name: 'Kristaps Porziņģis', position: 'Center' },
      { number: 9,  name: 'Derrick White',   position: 'Shooting Guard' },
      { number: 13, name: 'Luke Kornet',     position: 'Center' },
    ],
    recentResults: [
      { opponent: 'LA Lakers',    score: '92–89', result: 'W', date: '01/04/2024', tournament: 'NBA Playoffs' },
      { opponent: 'Heat',         score: '113–98', result: 'W', date: '27/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Knicks',       score: '107–99', result: 'W', date: '22/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Bucks',        score: '118–112', result: 'W', date: '17/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Philadelphia', score: '104–112', result: 'L', date: '10/03/2024', tournament: 'NBA Regular' },
    ],
  },
  'Sentinels': {
    name: 'Sentinels',
    shortName: 'SEN',
    stadium: 'Online / LAN',
    coach: 'Kaplan',
    founded: 2018,
    country: 'Mỹ',
    color: 'from-red-600 to-orange-600',
    players: [
      { number: 1, name: 'TenZ',     position: 'Duelist' },
      { number: 2, name: 'ShahZaM',  position: 'IGL / Initiator' },
      { number: 3, name: 'SicK',     position: 'Sentinel' },
      { number: 4, name: 'dapr',     position: 'Sentinel' },
      { number: 5, name: 'zombs',    position: 'Controller' },
    ],
    recentResults: [
      { opponent: 'LOUD',    score: '1–1', result: 'D', date: '01/04/2024', tournament: 'VCT Americas' },
      { opponent: 'NRG',     score: '2–0', result: 'W', date: '28/03/2024', tournament: 'VCT Americas' },
      { opponent: '100T',    score: '1–2', result: 'L', date: '22/03/2024', tournament: 'VCT Americas' },
      { opponent: 'C9',      score: '2–1', result: 'W', date: '17/03/2024', tournament: 'VCT Americas' },
      { opponent: 'EG',      score: '2–0', result: 'W', date: '10/03/2024', tournament: 'VCT Americas' },
    ],
  },
  'LOUD': {
    name: 'LOUD',
    shortName: 'LOUD',
    stadium: 'Online / LAN',
    coach: 'bzkA',
    founded: 2021,
    country: 'Brazil',
    color: 'from-green-500 to-lime-600',
    players: [
      { number: 1, name: 'aspas',    position: 'Duelist' },
      { number: 2, name: 'Less',     position: 'Duelist' },
      { number: 3, name: 'saadhak', position: 'IGL / Controller' },
      { number: 4, name: 'cauanzin',position: 'Initiator' },
      { number: 5, name: 'tuyz',    position: 'Sentinel' },
    ],
    recentResults: [
      { opponent: 'Sentinels', score: '1–1', result: 'D', date: '01/04/2024', tournament: 'VCT Americas' },
      { opponent: 'MIBR',      score: '2–0', result: 'W', date: '27/03/2024', tournament: 'VCT Americas' },
      { opponent: 'Leviatán',  score: '2–1', result: 'W', date: '21/03/2024', tournament: 'VCT Americas' },
      { opponent: 'NRG',       score: '0–2', result: 'L', date: '15/03/2024', tournament: 'VCT Americas' },
      { opponent: '100T',      score: '2–0', result: 'W', date: '08/03/2024', tournament: 'VCT Americas' },
    ],
  },
  'T1': {
    name: 'T1',
    shortName: 'T1',
    stadium: 'Online / LAN',
    coach: 'Kkoma',
    founded: 2003,
    country: 'Hàn Quốc',
    color: 'from-red-600 to-red-800',
    players: [
      { number: 1, name: 'Faker',   position: 'Mid' },
      { number: 2, name: 'Gumayusi', position: 'Bot' },
      { number: 3, name: 'Keria',   position: 'Support' },
      { number: 4, name: 'Zeus',    position: 'Top' },
      { number: 5, name: 'Oner',    position: 'Jungle' },
    ],
    recentResults: [
      { opponent: 'Gen.G',      score: '0–3', result: 'L', date: '31/03/2024', tournament: 'LCK Spring' },
      { opponent: 'KT Rolster', score: '3–1', result: 'W', date: '24/03/2024', tournament: 'LCK Spring' },
      { opponent: 'DRX',        score: '3–0', result: 'W', date: '17/03/2024', tournament: 'LCK Spring' },
      { opponent: 'Dplus KIA',  score: '2–3', result: 'L', date: '10/03/2024', tournament: 'LCK Spring' },
      { opponent: 'Hanwha',     score: '3–1', result: 'W', date: '03/03/2024', tournament: 'LCK Spring' },
    ],
  },
  'Gen.G': {
    name: 'Gen.G',
    shortName: 'GEN',
    stadium: 'Online / LAN',
    coach: 'cvMax',
    founded: 2017,
    country: 'Hàn Quốc',
    color: 'from-yellow-500 to-amber-600',
    players: [
      { number: 1, name: 'Chovy',   position: 'Mid' },
      { number: 2, name: 'Peyz',    position: 'Bot' },
      { number: 3, name: 'Delight', position: 'Support' },
      { number: 4, name: 'Doran',   position: 'Top' },
      { number: 5, name: 'Peanut',  position: 'Jungle' },
    ],
    recentResults: [
      { opponent: 'T1',         score: '3–0', result: 'W', date: '31/03/2024', tournament: 'LCK Spring' },
      { opponent: 'Hanwha',     score: '3–1', result: 'W', date: '25/03/2024', tournament: 'LCK Spring' },
      { opponent: 'KT Rolster', score: '3–2', result: 'W', date: '18/03/2024', tournament: 'LCK Spring' },
      { opponent: 'DRX',        score: '3–0', result: 'W', date: '11/03/2024', tournament: 'LCK Spring' },
      { opponent: 'Dplus KIA',  score: '1–3', result: 'L', date: '05/03/2024', tournament: 'LCK Spring' },
    ],
  },
  'NAVI': {
    name: 'NAVI',
    shortName: 'NAVI',
    stadium: 'Online / LAN',
    coach: 'B1ad3',
    founded: 2009,
    country: 'Ukraine',
    color: 'from-yellow-400 to-yellow-600',
    players: [
      { number: 1, name: 's1mple',    position: 'AWPer' },
      { number: 2, name: 'electronic', position: 'Rifler' },
      { number: 3, name: 'Perfecto',  position: 'Support' },
      { number: 4, name: 'b1t',       position: 'Rifler' },
      { number: 5, name: 'jL',        position: 'Support' },
    ],
    recentResults: [
      { opponent: 'FaZe Clan', score: '0–2', result: 'L', date: '01/04/2024', tournament: 'IEM Katowice' },
      { opponent: 'G2',        score: '2–1', result: 'W', date: '28/03/2024', tournament: 'ESL Pro League' },
      { opponent: 'Vitality',  score: '1–2', result: 'L', date: '22/03/2024', tournament: 'ESL Pro League' },
      { opponent: 'Astralis',  score: '2–0', result: 'W', date: '17/03/2024', tournament: 'BLAST Spring' },
      { opponent: 'Heroic',    score: '2–1', result: 'W', date: '11/03/2024', tournament: 'BLAST Spring' },
    ],
  },
  'FaZe Clan': {
    name: 'FaZe Clan',
    shortName: 'FaZe',
    stadium: 'Online / LAN',
    coach: 'NEO',
    founded: 2010,
    country: 'Quốc tế',
    color: 'from-red-700 to-orange-700',
    players: [
      { number: 1, name: 'karrigan',  position: 'IGL' },
      { number: 2, name: 'rain',      position: 'Rifler' },
      { number: 3, name: 'broky',     position: 'AWPer' },
      { number: 4, name: 'ropz',      position: 'Rifler' },
      { number: 5, name: 'frozen',    position: 'Rifler' },
    ],
    recentResults: [
      { opponent: 'NAVI',     score: '2–0', result: 'W', date: '01/04/2024', tournament: 'IEM Katowice' },
      { opponent: 'Vitality', score: '1–2', result: 'L', date: '25/03/2024', tournament: 'ESL Pro League' },
      { opponent: 'G2',       score: '2–0', result: 'W', date: '19/03/2024', tournament: 'ESL Pro League' },
      { opponent: 'Heroic',   score: '2–1', result: 'W', date: '13/03/2024', tournament: 'BLAST Spring' },
      { opponent: 'Astralis', score: '0–2', result: 'L', date: '07/03/2024', tournament: 'BLAST Spring' },
    ],
  },
  'Novak Djokovic': {
    name: 'Novak Djokovic',
    shortName: 'DJO',
    stadium: 'Centre Court',
    coach: 'Andy Murray (consultant)',
    founded: 2003,
    country: 'Serbia',
    color: 'from-blue-600 to-indigo-700',
    players: [
      { number: 1, name: 'Novak Djokovic', position: 'Tay vợt chính' },
    ],
    recentResults: [
      { opponent: 'Carlos Alcaraz', score: '6–4, 6–4', result: 'W', date: '15/03/2024', tournament: 'Indian Wells' },
      { opponent: 'Jannik Sinner',  score: '4–6, 2–6', result: 'L', date: '08/03/2024', tournament: 'Dubai' },
      { opponent: 'Holger Rune',    score: '6–3, 6–3', result: 'W', date: '01/03/2024', tournament: 'Dubai' },
      { opponent: 'Taylor Fritz',   score: '6–4, 7–5', result: 'W', date: '22/02/2024', tournament: 'Doha' },
      { opponent: 'Andrey Rublev',  score: '7–5, 6–4', result: 'W', date: '18/02/2024', tournament: 'Doha' },
    ],
  },
  'Carlos Alcaraz': {
    name: 'Carlos Alcaraz',
    shortName: 'ALC',
    stadium: 'Centre Court',
    coach: 'Juan Carlos Ferrero',
    founded: 2021,
    country: 'Tây Ban Nha',
    color: 'from-orange-500 to-red-600',
    players: [
      { number: 1, name: 'Carlos Alcaraz', position: 'Tay vợt chính' },
    ],
    recentResults: [
      { opponent: 'Novak Djokovic', score: '4–6, 4–6', result: 'L', date: '15/03/2024', tournament: 'Indian Wells' },
      { opponent: 'Daniil Medvedev', score: '7–6, 6–3', result: 'W', date: '10/03/2024', tournament: 'Indian Wells' },
      { opponent: 'Jannik Sinner',   score: '6–3, 6–2', result: 'W', date: '04/03/2024', tournament: 'Dubai' },
      { opponent: 'Holger Rune',     score: '6–4, 5–7, 6–4', result: 'W', date: '26/02/2024', tournament: 'Doha' },
      { opponent: 'Andy Murray',     score: '6–3, 6–4', result: 'W', date: '20/02/2024', tournament: 'Doha' },
    ],
  },
  'Golden State Warriors': {
    name: 'Golden State Warriors',
    shortName: 'GSW',
    stadium: 'Chase Center',
    coach: 'Steve Kerr',
    founded: 1946,
    country: 'Mỹ',
    color: 'from-yellow-400 to-blue-700',
    players: [
      { number: 30, name: 'Stephen Curry',   position: 'Point Guard' },
      { number: 11, name: 'Klay Thompson',   position: 'Shooting Guard' },
      { number: 23, name: 'Draymond Green',  position: 'Power Forward' },
      { number: 5,  name: 'Kevon Looney',    position: 'Center' },
      { number: 0, name: 'Andrew Wiggins',  position: 'Small Forward' },
    ],
    recentResults: [
      { opponent: 'Miami Heat',  score: '0–0 (upcoming)', result: 'D', date: 'Sắp diễn ra', tournament: 'NBA Regular' },
      { opponent: 'LA Lakers',   score: '110–121', result: 'L', date: '28/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Clippers',    score: '118–109', result: 'W', date: '22/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Rockets',     score: '122–101', result: 'W', date: '17/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Pelicans',    score: '104–107', result: 'L', date: '11/03/2024', tournament: 'NBA Regular' },
    ],
  },
  'Miami Heat': {
    name: 'Miami Heat',
    shortName: 'MIA',
    stadium: 'Kaseya Center',
    coach: 'Erik Spoelstra',
    founded: 1988,
    country: 'Mỹ',
    color: 'from-red-600 to-orange-500',
    players: [
      { number: 22, name: 'Jimmy Butler',    position: 'Small Forward' },
      { number: 14, name: 'Tyler Herro',     position: 'Shooting Guard' },
      { number: 11, name: 'Jaime Jáquez Jr.',position: 'Small Forward' },
      { number: 13, name: 'Bam Adebayo',    position: 'Center' },
      { number: 2,  name: 'Kyle Lowry',      position: 'Point Guard' },
    ],
    recentResults: [
      { opponent: 'Warriors',   score: 'Sắp diễn ra', result: 'D', date: 'Sắp diễn ra', tournament: 'NBA Regular' },
      { opponent: 'Celtics',    score: '98–113', result: 'L', date: '27/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Nets',       score: '120–105', result: 'W', date: '21/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Knicks',     score: '97–103', result: 'L', date: '15/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Magic',      score: '115–109', result: 'W', date: '09/03/2024', tournament: 'NBA Regular' },
    ],
  },
  'Manchester City': {
    name: 'Manchester City',
    shortName: 'MCI',
    stadium: 'Etihad Stadium',
    coach: 'Pep Guardiola',
    founded: 1880,
    country: 'Anh',
    color: 'from-sky-400 to-blue-600',
    players: [
      { number: 31, name: 'Ederson',         position: 'Thủ môn' },
      { number: 2,  name: 'Kyle Walker',     position: 'Hậu vệ' },
      { number: 3,  name: 'Rúben Dias',      position: 'Hậu vệ' },
      { number: 14, name: 'Aymeric Laporte', position: 'Hậu vệ' },
      { number: 7,  name: 'João Cancelo',    position: 'Hậu vệ' },
      { number: 16, name: 'Rodri',           position: 'Tiền vệ' },
      { number: 8,  name: 'Ilkay Gündogan', position: 'Tiền vệ' },
      { number: 20, name: 'Bernardo Silva',  position: 'Tiền vệ' },
      { number: 9,  name: 'Erling Haaland', position: 'Tiền đạo' },
      { number: 17, name: 'Kevin De Bruyne', position: 'Tiền vệ' },
      { number: 26, name: 'Phil Foden',      position: 'Tiền đạo' },
    ],
    recentResults: [
      { opponent: 'Dortmund',         score: '3–2', result: 'W', date: '01/04/2024', tournament: 'Bundesliga' },
      { opponent: 'Arsenal',          score: '0–0', result: 'D', date: '25/03/2024', tournament: 'Premier League' },
      { opponent: 'Liverpool',        score: '1–1', result: 'D', date: '16/03/2024', tournament: 'Premier League' },
      { opponent: 'Real Madrid',      score: '1–1', result: 'D', date: '09/04/2024', tournament: 'Champions League' },
      { opponent: 'Man United',       score: '3–1', result: 'W', date: '03/03/2024', tournament: 'Premier League' },
    ],
  },
  'Dortmund': {
    name: 'Borussia Dortmund',
    shortName: 'BVB',
    stadium: 'Signal Iduna Park',
    coach: 'Edin Terzić',
    founded: 1909,
    country: 'Đức',
    color: 'from-yellow-400 to-yellow-500',
    players: [
      { number: 1,  name: 'Gregor Kobel',   position: 'Thủ môn' },
      { number: 26, name: 'Mats Hummels',   position: 'Hậu vệ' },
      { number: 4,  name: 'Nico Schlotterbeck', position: 'Hậu vệ' },
      { number: 24, name: 'Thomas Meunier', position: 'Hậu vệ' },
      { number: 7,  name: 'Julian Brandt',  position: 'Tiền vệ' },
      { number: 11, name: 'Marco Reus',     position: 'Tiền vệ' },
      { number: 19, name: 'Emre Can',       position: 'Tiền vệ' },
      { number: 14, name: 'Donyell Malen',  position: 'Tiền đạo' },
      { number: 17, name: 'Karim Adeyemi',  position: 'Tiền đạo' },
      { number: 25, name: 'Sebastien Haller', position: 'Tiền đạo' },
    ],
    recentResults: [
      { opponent: 'Manchester City', score: '2–3', result: 'L', date: '01/04/2024', tournament: 'Bundesliga' },
      { opponent: 'Bayern Munich',   score: '0–2', result: 'L', date: '26/03/2024', tournament: 'Bundesliga' },
      { opponent: 'Hoffenheim',      score: '4–0', result: 'W', date: '20/03/2024', tournament: 'Bundesliga' },
      { opponent: 'PSV',             score: '2–0', result: 'W', date: '13/03/2024', tournament: 'Champions League' },
      { opponent: 'Stuttgart',       score: '2–3', result: 'L', date: '08/03/2024', tournament: 'Bundesliga' },
    ],
  },
  'Vitality': {
    name: 'Team Vitality',
    shortName: 'VIT',
    stadium: 'Online / LAN',
    coach: 'maLeK',
    founded: 2013,
    country: 'Pháp',
    color: 'from-yellow-400 to-yellow-600',
    players: [
      { number: 1, name: 'ZywOo',    position: 'AWPer' },
      { number: 2, name: 'apEX',     position: 'IGL' },
      { number: 3, name: 'Spinx',    position: 'Rifler' },
      { number: 4, name: 'flameZ',   position: 'Rifler' },
      { number: 5, name: 'Magisk',   position: 'Support' },
    ],
    recentResults: [
      { opponent: 'G2',       score: '2–0', result: 'W', date: '01/04/2024', tournament: 'BLAST Premier' },
      { opponent: 'FaZe',     score: '2–1', result: 'W', date: '25/03/2024', tournament: 'ESL Pro League' },
      { opponent: 'NAVI',     score: '2–1', result: 'W', date: '22/03/2024', tournament: 'ESL Pro League' },
      { opponent: 'Heroic',   score: '1–2', result: 'L', date: '16/03/2024', tournament: 'BLAST Spring' },
      { opponent: 'Astralis', score: '2–0', result: 'W', date: '10/03/2024', tournament: 'BLAST Spring' },
    ],
  },
  'G2': {
    name: 'G2 Esports',
    shortName: 'G2',
    stadium: 'Online / LAN',
    coach: 'Threat',
    founded: 2014,
    country: 'Đức',
    color: 'from-gray-700 to-gray-900',
    players: [
      { number: 1, name: 'NiKo',     position: 'Rifler' },
      { number: 2, name: 'huNter-',  position: 'Rifler' },
      { number: 3, name: 'jks',      position: 'Rifler' },
      { number: 4, name: 'nexa',     position: 'IGL' },
      { number: 5, name: 'Hooxi',    position: 'Support' },
    ],
    recentResults: [
      { opponent: 'Vitality', score: '0–2', result: 'L', date: '01/04/2024', tournament: 'BLAST Premier' },
      { opponent: 'FaZe',     score: '0–2', result: 'L', date: '19/03/2024', tournament: 'ESL Pro League' },
      { opponent: 'NAVI',     score: '1–2', result: 'L', date: '15/03/2024', tournament: 'ESL Pro League' },
      { opponent: 'Astralis', score: '2–1', result: 'W', date: '09/03/2024', tournament: 'BLAST Spring' },
      { opponent: 'Heroic',   score: '2–0', result: 'W', date: '03/03/2024', tournament: 'BLAST Spring' },
    ],
  },
  'Paper Rex': {
    name: 'Paper Rex',
    shortName: 'PRX',
    stadium: 'Online / LAN',
    coach: 'alecks',
    founded: 2020,
    country: 'Singapore',
    color: 'from-violet-600 to-purple-700',
    players: [
      { number: 1, name: 'mindfreak', position: 'Duelist' },
      { number: 2, name: 'f0rsakeN',  position: 'Duelist' },
      { number: 3, name: 'something', position: 'Initiator' },
      { number: 4, name: 'Jinggg',    position: 'Duelist' },
      { number: 5, name: 'bennyyy',   position: 'Controller' },
    ],
    recentResults: [
      { opponent: 'DRX',     score: '2–1', result: 'W', date: '01/04/2024', tournament: 'VCT Pacific' },
      { opponent: 'ZETA',    score: '2–0', result: 'W', date: '26/03/2024', tournament: 'VCT Pacific' },
      { opponent: 'T1',      score: '1–2', result: 'L', date: '20/03/2024', tournament: 'VCT Pacific' },
      { opponent: 'Rex Regum', score: '2–0', result: 'W', date: '14/03/2024', tournament: 'VCT Pacific' },
      { opponent: 'Global Esports', score: '2–1', result: 'W', date: '08/03/2024', tournament: 'VCT Pacific' },
    ],
  },
  'DRX': {
    name: 'DRX',
    shortName: 'DRX',
    stadium: 'Online / LAN',
    coach: 'termi',
    founded: 2019,
    country: 'Hàn Quốc',
    color: 'from-cyan-500 to-blue-600',
    players: [
      { number: 1, name: 'stax',   position: 'IGL / Controller' },
      { number: 2, name: 'Rb',     position: 'Initiator' },
      { number: 3, name: 'Zest',   position: 'Sentinel' },
      { number: 4, name: 'BuZz',   position: 'Initiator' },
      { number: 5, name: 'MaKo',   position: 'Controller' },
    ],
    recentResults: [
      { opponent: 'Paper Rex', score: '1–2', result: 'L', date: '01/04/2024', tournament: 'VCT Pacific' },
      { opponent: 'ZETA',      score: '2–0', result: 'W', date: '25/03/2024', tournament: 'VCT Pacific' },
      { opponent: 'PRX',       score: '1–2', result: 'L', date: '19/03/2024', tournament: 'VCT Pacific' },
      { opponent: 'T1',        score: '2–1', result: 'W', date: '13/03/2024', tournament: 'VCT Pacific' },
      { opponent: 'Gen.G',     score: '0–2', result: 'L', date: '07/03/2024', tournament: 'VCT Pacific' },
    ],
  },
  'Chicago Bulls': {
    name: 'Chicago Bulls',
    shortName: 'CHI',
    stadium: 'United Center',
    coach: 'Billy Donovan',
    founded: 1966,
    country: 'Mỹ',
    color: 'from-red-600 to-red-800',
    players: [
      { number: 10, name: 'DeMar DeRozan', position: 'Small Forward' },
      { number: 0,  name: 'Coby White',    position: 'Point Guard' },
      { number: 11, name: 'Ayo Dosunmu',   position: 'Shooting Guard' },
      { number: 35, name: 'Patrick Williams', position: 'Power Forward' },
      { number: 13, name: 'Torrey Craig',  position: 'Small Forward' },
    ],
    recentResults: [
      { opponent: 'New York Knicks', score: '105–112', result: 'L', date: '01/04/2024', tournament: 'NBA Regular' },
      { opponent: 'Indiana Pacers',  score: '118–112', result: 'W', date: '26/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Detroit Pistons', score: '101–97', result: 'W', date: '20/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Toronto Raptors', score: '108–116', result: 'L', date: '15/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Miami Heat',      score: '109–105', result: 'W', date: '09/03/2024', tournament: 'NBA Regular' },
    ],
  },
  'New York Knicks': {
    name: 'New York Knicks',
    shortName: 'NYK',
    stadium: 'Madison Square Garden',
    coach: 'Tom Thibodeau',
    founded: 1946,
    country: 'Mỹ',
    color: 'from-orange-500 to-blue-700',
    players: [
      { number: 9,  name: 'RJ Barrett',   position: 'Shooting Guard' },
      { number: 11, name: 'Jalen Brunson', position: 'Point Guard' },
      { number: 30, name: 'Julius Randle', position: 'Power Forward' },
      { number: 4,  name: 'Josh Hart',     position: 'Small Forward' },
      { number: 13, name: 'Evan Fournier', position: 'Shooting Guard' },
    ],
    recentResults: [
      { opponent: 'Chicago Bulls', score: '112–105', result: 'W', date: '01/04/2024', tournament: 'NBA Regular' },
      { opponent: 'Celtics',       score: '99–107', result: 'L', date: '22/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Heat',          score: '103–97', result: 'W', date: '15/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Nets',          score: '118–104', result: 'W', date: '10/03/2024', tournament: 'NBA Regular' },
      { opponent: 'Bucks',         score: '109–112', result: 'L', date: '05/03/2024', tournament: 'NBA Regular' },
    ],
  },
};

export function getTeamInfo(teamName: string): TeamInfo | undefined {
  // Tìm chính xác trước
  if (teamDatabase[teamName]) return teamDatabase[teamName];
  // Fallback: tìm không phân biệt hoa/thường
  const key = Object.keys(teamDatabase).find(
    (k) => k.toLowerCase() === teamName.toLowerCase()
  );
  return key ? teamDatabase[key] : undefined;
}